services:
  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: bomb0069/observability-user-service:lab-06-02
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      OTEL_SERVICE_NAME: user-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_RESOURCE_ATTRIBUTES: service.name=user-service
      OTEL_JAVAAGENT_EXTENSIONS: ./pyroscope-otel.jar
      PYROSCOPE_APPLICATION_NAME: user-service
      PYROSCOPE_SERVER_ADDRESS: http://lgtm:4040
      PYROSCOPE_FORMAT: jfr
    ports:
      - 8180:8080
    depends_on:
      lgtm:
        condition: service_started
      user-db:
        condition: service_healthy
      pyroscope:
        condition: service_started
    restart: always

  user-db:
    image: "postgres:16.3"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./user/tearup/init.sql:/docker-entrypoint-initdb.d/user.sql
    ports:
      - "5532:5432"
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $$POSTGRES_DB -h localhost -p 5432 -U $$POSTGRES_USER",
        ]
      interval: 10s
      timeout: 10s
      retries: 60

  store-service:
    image: bomb0069/observability-store-service:lab-06-02
    container_name: lab0602-store-service
    build:
      context: store
    ports:
      - "8100:8000"
    environment:
      DB_CONNECTION: user:password@(db:3306)/store
      SERVICE_NAME: store-service
      INSECURE_MODE: true
      OTEL_EXPORTER_OTLP_ENDPOINT: lgtm:4317
      PYROSCOPE_APPLICATION_NAME: store-service
      PYROSCOPE_SERVER_ADDRESS: http://lgtm:4040
    depends_on:
      db:
        condition: service_healthy
      pyroscope:
        condition: service_started
    restart: always

  point-service:
    image: bomb0069/observability-point-service:lab-06-02
    container_name: lab0602-point-service
    build:
      context: point
    ports:
      - "8101:8001"
    depends_on:
      db:
        condition: service_healthy
      pyroscope:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: user
      DB_PASSWORD: password
      OTEL_SERVICE_NAME: point-service
      OTEL_RESOURCE_ATTRIBUTES: service.name=point-service
    restart: always

  db:
    image: mysql:8.3.0
    container_name: lab0602-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./store/tearup/init.sql:/docker-entrypoint-initdb.d/store.sql
      - ./store/tearup/grantall.sql:/docker-entrypoint-initdb.d/grantall.sql
      - ./point/tearup/init.sql:/docker-entrypoint-initdb.d/point.sql
    ports:
      - "3406:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s

  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - "4140:4040"
    restart: always

  lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - "4417:4317"
      - "4418:4318"
      - "3100:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: lab0602-prometheus
    ports:
      - 9190:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
