{
 "title": "Apache Combined Logs - LGTM Stack",
 "tags": [
  "apache",
  "logs",
  "lgtm"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Status Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({app=\"flog\"} | regexp \"^(?P<remote_ip>[\\\\w\\\\.]+) - (?P<remote_user>[\\\\w\\\\-]+) \\\\[(?P<timestamp>[\\\\w:/]+\\\\s[+\\\\-]\\\\d{4})\\\\] \\\"(?P<method>\\\\w+) (?P<request_uri>[\\\\w\\\\.\\\\-\\\\/\\\\?=&%]+) (?P<protocol>[\\\\w\\\\/\\\\.]+)\\\" (?P<status>\\\\d{3}) (?P<bytes_sent>\\\\d+) \\\"(?P<http_referer>[^\\\"]*)\\\" \\\"(?P<user_agent>[^\\\"]*)\\\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"flog\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Top 10 Requesting IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum(count_over_time({app=\"flog\"} | regexp \"^(?P<remote_ip>[\\\\w\\\\.]+) - (?P<remote_user>[\\\\w\\\\-]+) \\\\[(?P<timestamp>[\\\\w:/]+\\\\s[+\\\\-]\\\\d{4})\\\\] \\\"(?P<method>\\\\w+) (?P<request_uri>[\\\\w\\\\.\\\\-\\\\/\\\\?=&%]+) (?P<protocol>[\\\\w\\\\/\\\\.]+)\\\" (?P<status>\\\\d{3}) (?P<bytes_sent>\\\\d+) \\\"(?P<http_referer>[^\\\"]*)\\\" \\\"(?P<user_agent>[^\\\"]*)\\\"\" [$__range])) by (remote_ip))"
    }
   ]
  },
  {
   "title": "Traffic Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"flog\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "HTTP Methods Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method) (count_over_time({app=\"flog\"} | regexp \"^(?P<remote_ip>[\\\\w\\\\.]+) - (?P<remote_user>[\\\\w\\\\-]+) \\\\[(?P<timestamp>[\\\\w:/]+\\\\s[+\\\\-]\\\\d{4})\\\\] \\\"(?P<method>\\\\w+) (?P<request_uri>[\\\\w\\\\.\\\\-\\\\/\\\\?=&%]+) (?P<protocol>[\\\\w\\\\/\\\\.]+)\\\" (?P<status>\\\\d{3}) (?P<bytes_sent>\\\\d+) \\\"(?P<http_referer>[^\\\"]*)\\\" \\\"(?P<user_agent>[^\\\"]*)\\\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Apache Access Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"flog\"}"
    }
   ]
  },
  {
   "title": "Top 10 Request URIs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(10, sum by (request_uri) (count_over_time({app=\"flog\"} | regexp \"^(?P<remote_ip>[\\\\w\\\\.]+) - (?P<remote_user>[\\\\w\\\\-]+) \\\\[(?P<timestamp>[\\\\w:/]+\\\\s[+\\\\-]\\\\d{4})\\\\] \\\"(?P<method>\\\\w+) (?P<request_uri>[\\\\w\\\\.\\\\-\\\\/\\\\?=&%]+) (?P<protocol>[\\\\w\\\\/\\\\.]+)\\\" (?P<status>\\\\d{3}) (?P<bytes_sent>\\\\d+) \\\"(?P<http_referer>[^\\\"]*)\\\" \\\"(?P<user_agent>[^\\\"]*)\\\"\" [$__interval])))"
    }
   ]
  }
 ]
}